INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Steven%20A.%20Cholewiak
INFO:scholarly:Found 1 authors
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:10:26] "[37mGET / HTTP/1.1[0m" 200 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Steven%20A.%20Cholewiak
INFO:scholarly:Found 1 authors
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:10:49] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:12:30] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:13:14] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:13:32] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:13:46] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:13:56] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    return scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:15:10] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:15:25] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:15:48] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:15:57] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:16:58] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:17:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:18:41] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:19:02] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:19:07] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 10, in search_author
    print (content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:20:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 11, in search_author
    search_query = scholarly.search_author(content.name)
AttributeError: 'dict' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:22:21] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 12, in search_author
    return jsonify(search_query)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:22:42] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a generator.
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:22:57] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a generator.
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:23:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 13, in search_author
    return json.dumps(search_query)
NameError: name 'json' is not defined
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:24:48] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 14, in search_author
    return json.dumps(search_query, mimetype='application/json')
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
TypeError: __init__() got an unexpected keyword argument 'mimetype'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:25:29] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 14, in search_author
    return jsonify(search_query)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:26:10] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 14, in search_author
    return jsonify(search_query)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:27:28] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 14, in search_author
    return jsonify(search_query)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:27:54] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 14, in search_author
    return jsonify(search_query)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:27:57] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 14, in search_author
    return jsonify(search_query), 200
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:28:34] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 13, in search_author
    print(search_query.len())
AttributeError: 'generator' object has no attribute 'len'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:29:12] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 13, in search_author
    print(search_query.len())
AttributeError: 'generator' object has no attribute 'len'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:29:13] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 15, in search_author
    return jsonify(results), 200
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:30:22] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 14, in search_author
    print(results.len())
AttributeError: 'list' object has no attribute 'len'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:31:12] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 15, in search_author
    return jsonify(results), 200
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:32:01] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 15, in search_author
    return jsonify(results), 200
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:32:18] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 15, in search_author
    return jsonify(results)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:32:27] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 15, in search_author
    return jsonify({results:[results]})
TypeError: unhashable type: 'list'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:33:18] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 15, in search_author
    return jsonify({items:[results]})
NameError: name 'items' is not defined
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:34:25] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 15, in search_author
    return jsonify(results)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:35:58] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 15, in search_author
    return jsonify(results)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:36:33] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return jsonify(results)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:36:54] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return jsonify(results)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:37:52] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return jsonify(results)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:38:05] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return jsonify(results)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:38:18] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return jsonify(results[2])
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:39:37] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:43:40] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return json.dumps(results)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:44:19] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return json.dumps(results)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:44:28] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return jsonify(results[2])
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:45:49] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
ERROR:app:Exception on /search_author [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jmanderson/dev/scholarly_server/app.py", line 16, in search_author
    return jsonify(results[2])
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Author is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:46:03] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:46:13] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Steven%20A.%20Cholewiak
INFO:scholarly:Found 1 authors
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:51:08] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:52:14] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:52:31] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:54:43] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:55:22] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:56:48] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:58:33] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=John%20Anderson
INFO:scholarly:Found 10 authors
INFO:scholarly:Loading next page of authors
INFO:scholarly:Getting https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=John+Anderson&after_author=7IyWACjo__8J&astart=10
INFO:scholarly:Found 10 authors
INFO:scholarly:Loading next page of authors
INFO:scholarly:Getting https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=John+Anderson&after_author=dlYAABX7__8J&astart=20
INFO:scholarly:Found 10 authors
INFO:scholarly:Loading next page of authors
INFO:scholarly:Getting https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=John+Anderson&after_author=-wC3AL7-__8J&astart=30
INFO:scholarly:Found 10 authors
INFO:scholarly:Loading next page of authors
INFO:scholarly:Getting https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=John+Anderson&after_author=hSkCAfr___8J&astart=40
INFO:scholarly:Found 5 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:58:58] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=John%20Malcolm%20Anderson
INFO:scholarly:Found 0 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:59:24] "[37mGET /search_author HTTP/1.1[0m" 200 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=John%20Malcolm%20A
INFO:scholarly:Found 1 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 21:59:39] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=John%20Malcolm%20A
INFO:scholarly:Found 1 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:00:28] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:01:36] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:01:55] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:02:35] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=John%20Malcolm%20A
INFO:scholarly:Found 1 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:02:51] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=John%20Malcolm%20A
INFO:scholarly:Found 1 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:03:20] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=John%20Malcolm%20A
INFO:scholarly:Found 1 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:06:08] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=John%20Malcolm%20A
INFO:scholarly:Found 1 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:07:27] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:09:35] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:09:55] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:09:59] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:11:22] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:14:20] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:14:44] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:15:14] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:15:39] "[37mGET /search_author HTTP/1.1[0m" 200 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:17:24] "[37mGET /search_author HTTP/1.1[0m" 200 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:19:58] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:20:21] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:21:44] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:22:02] "[37mGET /search_author HTTP/1.1[0m" 200 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:22:33] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:22:54] "[37mGET /search_author HTTP/1.1[0m" 200 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:23:04] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:23:09] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:23:15] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:23:45] "[37mGET /search_author HTTP/1.1[0m" 200 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:24:12] "[35m[1mGET /search_author HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:24:36] "[37mGET /search_author HTTP/1.1[0m" 200 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:26:32] "[37mGET /search_author HTTP/1.1[0m" 200 -
INFO:werkzeug: * Detected change in '/Users/jmanderson/dev/scholarly_server/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Alexander%20Kondakov
INFO:scholarly:Found 3 authors
INFO:scholarly:No more author pages
INFO:werkzeug:127.0.0.1 - - [06/Sep/2020 22:27:21] "[37mGET /search_author HTTP/1.1[0m" 200 -
